version: '3.0' # specify docker-compose version

# Define the services/ containers to be run
services:
 redis:
  image: redis:alpine

 express_1: # name of the first express
  build: server # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping  
  depends_on:
  - redis

 express_2: # name of the second express
  build: server # specify the directory of the Dockerfile
  ports:
  - "3001:3000" #specify ports mapping
  depends_on:
  - redis

 angular_1: # name of the first client
  build: 
    context: client\obligo-client # specify the directory of the Dockerfile
    dockerfile: dev.dockerfile
  ports:
  - "4200:4200" # specify port mapping
  depends_on:
  - express_1
  
 angular_2: # name of the second client
  build:
    context: client\obligo-client # specify the directory of the Dockerfile
    dockerfile: prod.dockerfile
  ports:
  - "4300:4200" # specify port mapping
  depends_on:
  - express_2