version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 express: # name of the second service
  build: server # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping

 angular: # name of the first service
  build: client\obligo-client # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping
 